language: python
python:
  - "2.7"
  - "3.6"

env:
  - SPHINX_SPEC=Sphinx~=1.4.0
  - SPHINX_SPEC=Sphinx~=1.5.0
  - SPHINX_SPEC=Sphinx~=1.6.0
  - SPHINX_SPEC=git+https://github.com/sphinx-doc/sphinx.git\#egg\=Sphinx-dev

matrix:
  exclude:  # Sphinx >= 2.0 does not work with python2.7
  - python: 2.7
    env: SPHINX_SPEC=git+https://github.com/sphinx-doc/sphinx.git\#egg\=Sphinx-dev

# before_install:
#   - bundle install

install:
  - pip install coveralls
  - pip install sphinx_rtd_theme
  - pip install $SPHINX_SPEC --allow-external Sphinx --allow-unverified Sphinx
  - python setup.py install

script:
  - coverage run --source=hieroglyph setup.py test
  # - rake jasmine:ci JASMINE_CONFIG_PATH=./src/jstests/jasmine.yml
  - cd docs; READTHEDOCS=True SPHINXOPTS="-NqW" SPHINXBUILD="sphinx-build" make -e clean html slides

after_success:
  - coveralls
